# This is a basic workflow to help you get started with Actions

name: auto-deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PRODUCTION_ENV: ${{secrets.PRODUCTION_ENV}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # set java
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Install SSH key
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.NOVEMBER_UBUNTU_SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.NOVEMBER_UBUNTU_KNOWN_HOSTS }}
          config: ${{ secrets.NOVEMBER_UBUNTU_SSH_CONFIG }} # ssh_config; optional
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      # prepare gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      # Create production env
      - name: Create production env
        run: |
          touch src/main/resources/application.properties
          echo "${{ secrets.PRODUCTION_ENV }}" > src/main/resources/application.properties
      # build war file
      - name: Build with Gradle
        run: |
          make production.build
          echo build end.
      - name: Deploy Cataria project
        run: |
          make production.deploy